# Generated by Django 5.2.8 on 2025-11-23 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_contactmessage_sitesetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='allow_comments',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='allow_registration',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='contact_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='facebook_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='instagram_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='posts_per_page',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='site_favicon',
            field=models.ImageField(blank=True, null=True, upload_to='site_favicon/'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='site_logo',
            field=models.ImageField(blank=True, null=True, upload_to='site_logo/'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='twitter_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='youtube_url',
            field=models.URLField(blank=True),
        ),
    ]
