# Generated by Django 5.2.8 on 2025-12-06 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_order_stripe_checkout_session_id_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.RemoveField(
            model_name='bookmark',
            name='course',
        ),
        migrations.RemoveField(
            model_name='bookmark',
            name='post',
        ),
    ]
