# Generated by Django 5.2.8 on 2025-12-06 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def delete_null_bookmarks(apps, schema_editor):
    Bookmark = apps.get_model('blog', 'Bookmark')
    # delete bookmarks with missing content_type or object_id to avoid NOT NULL conflicts
    qs1 = Bookmark.objects.filter(content_type__isnull=True)
    if qs1.exists():
        qs1.delete()
    qs2 = Bookmark.objects.filter(object_id__isnull=True)
    if qs2.exists():
        qs2.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_alter_bookmark_unique_together_bookmark_content_type_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(delete_null_bookmarks, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='bookmark',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='object_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together={('user', 'content_type', 'object_id')},
        ),
    ]
