# Generated by Django 5.2.8 on 2025-12-06 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_alter_bookmark_content_type_alter_bookmark_object_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='certificate_templates/')),
                ('html_content', models.TextField(help_text='Use {{ student_name }}, {{ course_name }}, {{ completion_date }}, {{ certificate_id }} as placeholders.')),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='last_viewed',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='time_spent',
            field=models.PositiveIntegerField(default=0, help_text='Time spent in seconds'),
        ),
        migrations.AddField(
            model_name='course',
            name='certificate_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.certificatetemplate'),
        ),
    ]
